"""Generate iCalendar (.ics) feed of upcoming subscription renewals."""
from __future__ import annotations

import uuid
from datetime import datetime, timedelta
from pathlib import Path

from db import get_conn


def _escape(text: str) -> str:
    return (text or "").replace("\\", "\\\\").replace(",", "\\,").replace(";", "\\;").replace("\n", "\\n")


def build_ics() -> str:
    """Return an .ics calendar string with one all-day event per upcoming renewal."""
    conn = get_conn()
    rows = conn.execute(
        "SELECT id, name, cost, currency, billing_cycle, next_billing_date, "
        "       last_charge_date, notes "
        "FROM subscriptions WHERE active = 1 AND next_billing_date IS NOT NULL "
        "ORDER BY next_billing_date"
    ).fetchall()

    now_utc = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//Pulse//Subscription renewals//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        "X-WR-CALNAME:Pulse — Subscription renewals",
        "X-WR-CALDESC:Generated by Pulse — your money & time, in rhythm.",
    ]
    for r in rows:
        try:
            d = datetime.fromisoformat(r["next_billing_date"]).date()
        except Exception:
            continue
        # All-day event
        d_end = d + timedelta(days=1)
        uid = f"sub-{r['id']}-{d.isoformat()}@lifetracker.local"
        title = f"{_escape(r['name'])} renews ({r['cost']:.2f} {r['currency']} / {r['billing_cycle']})"
        desc = _escape(
            f"Next charge: {d.isoformat()}\\n"
            f"Cost: {r['cost']:.2f} {r['currency']} / {r['billing_cycle']}\\n"
            f"{r['notes'] or ''}"
        )
        lines += [
            "BEGIN:VEVENT",
            f"UID:{uid}",
            f"DTSTAMP:{now_utc}",
            f"DTSTART;VALUE=DATE:{d.strftime('%Y%m%d')}",
            f"DTEND;VALUE=DATE:{d_end.strftime('%Y%m%d')}",
            f"SUMMARY:{title}",
            f"DESCRIPTION:{desc}",
            "BEGIN:VALARM",
            "ACTION:DISPLAY",
            "DESCRIPTION:Subscription renewal reminder",
            "TRIGGER:-P3D",  # 3 days before
            "END:VALARM",
            "END:VEVENT",
        ]
    lines.append("END:VCALENDAR")
    return "\r\n".join(lines)


def write_ics(path: Path | None = None) -> Path:
    if path is None:
        path = Path(__file__).parent / "data" / "subscriptions.ics"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_ics(), encoding="utf-8")
    return path


if __name__ == "__main__":
    p = write_ics()
    print(f"wrote {p}, {p.stat().st_size} bytes")
