[theme]
base = "light"
primaryColor = "#10b981"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f7f9"
textColor = "#0a0b0f"
font = "sans serif"

[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
