[theme]
base = "light"
primaryColor = "#00C58A"
backgroundColor = "#FAFAF7"
secondaryBackgroundColor = "#F4F4F0"
textColor = "#0A0A0F"
font = "sans serif"

[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
